### ISSUE TITLE
Implement the model

### ISSUE THREAD

**Issue by adambarla** [adambarla/NMT-augment#2]
We use BERT as the NN architecture. The encoder of the model is a pre-trained XLM-RoBERTa.
We’ll start with a pre-trained model, such as XLM-RoBERTa, known for its strong language understanding and generation capabilities. Then we add a decoder to the pre-trained model to obtain an end-to-end machine translation model.

**Comment by AmashiNiw** [comment]
> The encoder of the model is a pre-trained XLM-RoBERTa

If the pre-trained model has already been trained on the _simulated_ low-resource language, it might not accurately reflect the performance benefits of data augmentation, as the model has already seen a significant amount of data in that language during pre-training. Either training a full model from scratch, or choosing a language that has not been used for pretraining would be our options

**Comment by adambarla** [comment]
Makes sense. The description is what we wrote in the proposal. Which option do you suggest? Finding a dataset with language that the pre-trained XLM-RoBERTa hasn't seen yet might be hard.

**Comment by AmashiNiw** [comment]
I concur. A simple transformer based model should be a good starting point. That would give us more control over the insights we draw from our results.
