### ISSUE TITLE
implement word level tokenizer

### ISSUE THREAD

**Issue by adambarla** [adambarla/NMT-augment#25]
- create a new branch
- look at the implementation of `CharacterTokenizer` in `src/tokenizer/character.py`
- implement a `WordTokenizer` wrapper with the same API as `CharacterTokenizer` (also some properties need to exist with the same name such as `self.pad_token_id`, look what is used in the code). use `spacy` or whatever you deem best.
- create a `word.yaml` config in the `conf/tokenizer` directory with `_target_` field (inspiration in `character.yaml`)
- to run your tokenizer add `tokenizer=word` to the training prompt 
- create a pull request

**Comment by DecayingSeart** [comment]
see pull request. Need testing though.

**Comment by adambarla** [comment]
#27
