### ISSUE TITLE
Add language selectablility for synonym aug

### ISSUE THREAD

**Issue by AmashiNiw** [adambarla/NMT-augment#41]

**Comment by adambarla** [comment]
What do you mean by this please?

**Comment by AmashiNiw** [comment]
The augmentation is replacing words in a sentence by synonyms of those words. 
e.g. 
> Original English: "The cat is sleeping."
> Synonym Augmented English: "The feline is dozing."

We can do this for either target lang, source or both (this is where the option to select one is needed). Currently I'm doing both.

Unfortunately synonm data isn't available for Czech `(supported_langs = ['als', 'arb', 'bul', 'cat', 'cmn', 'dan', 'ell', 'eng', 'eus',
'fin', 'fra', 'glg', 'heb', 'hrv', 'ind', 'isl', 'ita', 'ita_iwn', 'jpn', 'lit', 'nld', 'nno', 'nob', 'pol', 'por', 'ron', 'slk', 'slv', 'spa', 'swe', 'tha', 'zsm']).` 

We might have to switch to a language pair like fr-en.

**Comment by adambarla** [comment]
I edited how language selection through hyperparameters works. If you pull the current main to your branch you should be able to change it by `data.l1=<smt>` or `data.l2=<smt>`. French or German would be nice :)
